baseURL = "https://eddieabbondanz.io"
languageCode = "en-us"
title = "Eddie Abbondanzio"
theme = "blank"
canonifyurls = true
pagination.pagerSize = 10
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"
summaryLength = 30

[markup.goldmark.renderer]
unsafe= true

[blackfriday]
    smartypants = false

[taxonomies]
    category = "categories"
    series = "series"

[params]
    author = "Eddie Abbondanzio"
    description = "My blog about my project cars and other contraptions"
    creationYear = 2013
    avatar = "/img/avatar.jpg" 
    github = "http://github.com/EddieAbbondanzio"
    linkedin = "https://www.linkedin.com/in/ed-abbondanzio-5a7378208/"
    defaultPostThumbnailPath = "images/thumbnail.jpg"

[menu]
    [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "post"
    weight = 1

    [[menu.main]]
    name = "Development"
    identifier = "development"
    parent = "posts"
    url="/categories/development"
    weight = 1

    [[menu.main]]
    name = "LS XJ Build"
    identifier = "ls-xj-build"
    parent = "posts"
    url="/categories/ls-xj-build"
    weight = 2

    [[menu.main]]
    name = "OEM+ XJ Build"
    identifier = "oem+-xj-build"
    parent = "posts"
    url="/categories/oem+-xj-build"
    weight = 3

    [[menu.main]]
    name = "93 EG Hatch Build"
    identifier = "93-eg-hatch-build"
    parent = "posts"
    url="/categories/93-eg-hatch-build"
    weight = 4

    [[menu.main]]
    name = "88 Integra Build"
    identifier = "88-integra-build"
    parent = "posts"
    url="/categories/88-integra-build"
    weight = 5

    [[menu.main]]
    name = "Honda Info and DIYs"
    identifier = "honda-info-and-diys"
    parent = "posts"
    url="/categories/honda-info-and-diys"
    weight = 6

    [[menu.main]]
    name = "XJ Info and DIYs"
    identifier = "xj-info-and-diys"
    parent = "posts"
    url="/categories/xj-info-and-diys"
    weight = 7

    [[menu.main]]
    name = "Shop and Tools"
    identifier = "shop-and-tools"
    parent = "posts"
    url="/categories/shop-and-tools"
    weight = 8

    [[menu.main]]
    identifier = "apps"
    name = "Apps"
    url = "app"
    weight = 2
    
    [[menu.main]]
    identifier = "about-me"
    name = "About"
    url = "about"
    weight = 4

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"
